// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(polar_coreFFI)
import polar_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_polar_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_polar_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePolarCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct AltAzCoord {
    public var altDeg: Double
    public var azDeg: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(altDeg: Double, azDeg: Double) {
        self.altDeg = altDeg
        self.azDeg = azDeg
    }
}

#if compiler(>=6)
extension AltAzCoord: Sendable {}
#endif


extension AltAzCoord: Equatable, Hashable {
    public static func ==(lhs: AltAzCoord, rhs: AltAzCoord) -> Bool {
        if lhs.altDeg != rhs.altDeg {
            return false
        }
        if lhs.azDeg != rhs.azDeg {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(altDeg)
        hasher.combine(azDeg)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAltAzCoord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AltAzCoord {
        return
            try AltAzCoord(
                altDeg: FfiConverterDouble.read(from: &buf), 
                azDeg: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: AltAzCoord, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.altDeg, into: &buf)
        FfiConverterDouble.write(value.azDeg, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAltAzCoord_lift(_ buf: RustBuffer) throws -> AltAzCoord {
    return try FfiConverterTypeAltAzCoord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAltAzCoord_lower(_ value: AltAzCoord) -> RustBuffer {
    return FfiConverterTypeAltAzCoord.lower(value)
}


public struct CelestialCoord {
    public var raDeg: Double
    public var decDeg: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(raDeg: Double, decDeg: Double) {
        self.raDeg = raDeg
        self.decDeg = decDeg
    }
}

#if compiler(>=6)
extension CelestialCoord: Sendable {}
#endif


extension CelestialCoord: Equatable, Hashable {
    public static func ==(lhs: CelestialCoord, rhs: CelestialCoord) -> Bool {
        if lhs.raDeg != rhs.raDeg {
            return false
        }
        if lhs.decDeg != rhs.decDeg {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(raDeg)
        hasher.combine(decDeg)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCelestialCoord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CelestialCoord {
        return
            try CelestialCoord(
                raDeg: FfiConverterDouble.read(from: &buf), 
                decDeg: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: CelestialCoord, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.raDeg, into: &buf)
        FfiConverterDouble.write(value.decDeg, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCelestialCoord_lift(_ buf: RustBuffer) throws -> CelestialCoord {
    return try FfiConverterTypeCelestialCoord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCelestialCoord_lower(_ value: CelestialCoord) -> RustBuffer {
    return FfiConverterTypeCelestialCoord.lower(value)
}


public struct PolarError {
    public var altErrorArcmin: Double
    public var azErrorArcmin: Double
    public var totalErrorArcmin: Double
    public var mountAxis: CelestialCoord

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(altErrorArcmin: Double, azErrorArcmin: Double, totalErrorArcmin: Double, mountAxis: CelestialCoord) {
        self.altErrorArcmin = altErrorArcmin
        self.azErrorArcmin = azErrorArcmin
        self.totalErrorArcmin = totalErrorArcmin
        self.mountAxis = mountAxis
    }
}

#if compiler(>=6)
extension PolarError: Sendable {}
#endif


extension PolarError: Equatable, Hashable {
    public static func ==(lhs: PolarError, rhs: PolarError) -> Bool {
        if lhs.altErrorArcmin != rhs.altErrorArcmin {
            return false
        }
        if lhs.azErrorArcmin != rhs.azErrorArcmin {
            return false
        }
        if lhs.totalErrorArcmin != rhs.totalErrorArcmin {
            return false
        }
        if lhs.mountAxis != rhs.mountAxis {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(altErrorArcmin)
        hasher.combine(azErrorArcmin)
        hasher.combine(totalErrorArcmin)
        hasher.combine(mountAxis)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePolarError: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PolarError {
        return
            try PolarError(
                altErrorArcmin: FfiConverterDouble.read(from: &buf), 
                azErrorArcmin: FfiConverterDouble.read(from: &buf), 
                totalErrorArcmin: FfiConverterDouble.read(from: &buf), 
                mountAxis: FfiConverterTypeCelestialCoord.read(from: &buf)
        )
    }

    public static func write(_ value: PolarError, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.altErrorArcmin, into: &buf)
        FfiConverterDouble.write(value.azErrorArcmin, into: &buf)
        FfiConverterDouble.write(value.totalErrorArcmin, into: &buf)
        FfiConverterTypeCelestialCoord.write(value.mountAxis, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolarError_lift(_ buf: RustBuffer) throws -> PolarError {
    return try FfiConverterTypePolarError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolarError_lower(_ value: PolarError) -> RustBuffer {
    return FfiConverterTypePolarError.lower(value)
}


public struct StarCentroid {
    public var x: Double
    public var y: Double
    public var brightness: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Double, y: Double, brightness: Double) {
        self.x = x
        self.y = y
        self.brightness = brightness
    }
}

#if compiler(>=6)
extension StarCentroid: Sendable {}
#endif


extension StarCentroid: Equatable, Hashable {
    public static func ==(lhs: StarCentroid, rhs: StarCentroid) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        if lhs.brightness != rhs.brightness {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
        hasher.combine(brightness)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStarCentroid: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StarCentroid {
        return
            try StarCentroid(
                x: FfiConverterDouble.read(from: &buf), 
                y: FfiConverterDouble.read(from: &buf), 
                brightness: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: StarCentroid, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
        FfiConverterDouble.write(value.brightness, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStarCentroid_lift(_ buf: RustBuffer) throws -> StarCentroid {
    return try FfiConverterTypeStarCentroid.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStarCentroid_lower(_ value: StarCentroid) -> RustBuffer {
    return FfiConverterTypeStarCentroid.lower(value)
}


public enum AlignmentError: Swift.Error {

    
    
    case CollinearPoints(message: String)
    
    case InvalidCoordinates(message: String)
    
    case ComputationFailed(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlignmentError: FfiConverterRustBuffer {
    typealias SwiftType = AlignmentError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlignmentError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .CollinearPoints(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidCoordinates(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .ComputationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AlignmentError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .CollinearPoints(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidCoordinates(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .ComputationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlignmentError_lift(_ buf: RustBuffer) throws -> AlignmentError {
    return try FfiConverterTypeAlignmentError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlignmentError_lower(_ value: AlignmentError) -> RustBuffer {
    return FfiConverterTypeAlignmentError.lower(value)
}


extension AlignmentError: Equatable, Hashable {}




extension AlignmentError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}



/**
 * Angular separation between two celestial positions (degrees).
 */
public func angularSeparation(a: CelestialCoord, b: CelestialCoord) -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_polar_core_fn_func_angular_separation(
        FfiConverterTypeCelestialCoord_lower(a),
        FfiConverterTypeCelestialCoord_lower(b),$0
    )
})
}
/**
 * Convert equatorial coordinates to horizontal (alt/az).
 */
public func celestialToAltaz(coord: CelestialCoord, observerLatDeg: Double, observerLonDeg: Double, timestampJd: Double) -> AltAzCoord  {
    return try!  FfiConverterTypeAltAzCoord_lift(try! rustCall() {
    uniffi_polar_core_fn_func_celestial_to_altaz(
        FfiConverterTypeCelestialCoord_lower(coord),
        FfiConverterDouble.lower(observerLatDeg),
        FfiConverterDouble.lower(observerLonDeg),
        FfiConverterDouble.lower(timestampJd),$0
    )
})
}
/**
 * Compute polar alignment error from three plate-solved positions.
 */
public func computePolarError(pos1: CelestialCoord, pos2: CelestialCoord, pos3: CelestialCoord, observerLatDeg: Double, observerLonDeg: Double, timestampJd: Double)throws  -> PolarError  {
    return try  FfiConverterTypePolarError_lift(try rustCallWithError(FfiConverterTypeAlignmentError_lift) {
    uniffi_polar_core_fn_func_compute_polar_error(
        FfiConverterTypeCelestialCoord_lower(pos1),
        FfiConverterTypeCelestialCoord_lower(pos2),
        FfiConverterTypeCelestialCoord_lower(pos3),
        FfiConverterDouble.lower(observerLatDeg),
        FfiConverterDouble.lower(observerLonDeg),
        FfiConverterDouble.lower(timestampJd),$0
    )
})
}
/**
 * Compute Julian Date from UTC date/time components.
 */
public func julianDate(year: Int32, month: UInt32, day: UInt32, hour: UInt32, min: UInt32, sec: Double) -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_polar_core_fn_func_julian_date(
        FfiConverterInt32.lower(year),
        FfiConverterUInt32.lower(month),
        FfiConverterUInt32.lower(day),
        FfiConverterUInt32.lower(hour),
        FfiConverterUInt32.lower(min),
        FfiConverterDouble.lower(sec),$0
    )
})
}
/**
 * Compute local sidereal time in degrees.
 */
public func localSiderealTime(jd: Double, longitudeDeg: Double) -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_polar_core_fn_func_local_sidereal_time(
        FfiConverterDouble.lower(jd),
        FfiConverterDouble.lower(longitudeDeg),$0
    )
})
}
/**
 * Library version string.
 */
public func polarCoreVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_polar_core_fn_func_polar_core_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_polar_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_polar_core_checksum_func_angular_separation() != 76) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_polar_core_checksum_func_celestial_to_altaz() != 54904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_polar_core_checksum_func_compute_polar_error() != 29002) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_polar_core_checksum_func_julian_date() != 38302) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_polar_core_checksum_func_local_sidereal_time() != 23246) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_polar_core_checksum_func_polar_core_version() != 23056) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePolarCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all